site_name: Arya XAI Documentation

site_url: http://docs.arya-xai.ai/

nav:
    - Home: index.md
    - Algorithm: algo.md
    - Let's Get Started: use_the_api.md
    - Example: examples.md
    - Network Details: network_detail.md
    - Layer Types: Layer_types.md
    - About: about.md

theme: readthedocs